Repository bittide/bittide-hardware, pull requests merged in 2023-01, with the labels that each got.

#214 Expose read/write data ports of elastic buffer
  bittide-instances/src/Bittide/Instances/ElasticBuffer.hs
  bittide-instances/src/Bittide/Instances/MVPs.hs
  bittide/src/Bittide/ElasticBuffer.hs
  bittide/tests/Tests/ElasticBuffer.hs
Labels: 1

#220 Add `scatterUnitWb` and `gatherUnitWb` instances
  .github/workflows/ci.yml
  bittide-instances/bin/Shake.hs
  bittide-instances/bittide-instances.cabal
  bittide-instances/src/Bittide/Instances/ScatterGather.hs
Labels: 2

#222 Add missing shake instances to CI
  .github/workflows/ci.yml
Labels: 3

#244 Rust updates, making VexRiscv tests error on missing binaries
  .github/workflows/ci.yml
  firmware/bittide-sys/src/panic_handler.rs
  firmware/bittide-sys/tests/elf_common.rs
  firmware/bittide-sys/tests/elf_loading.rs
  firmware/examples/fdt-read/build.rs
  firmware/examples/fdt-read/src/main.rs
  firmware/examples/hello/build.rs
  firmware/tests/build.rs
  rust-toolchain.toml
  vex-riscv/tests/tests.hs
  vex-riscv/vex-test-programs/build.rs
  vex-riscv/vex-test-programs/src/bin/loop_write.rs
  vex-riscv/vex-test-programs/src/bin/single_write.rs
Labels: needs review
