Repository bittide/bittide-hardware, pull requests merged in 2024-04, with the labels that each got.

#491 Error for unmapped addresses in `singleMasterInterconnect`
  bittide-instances/bittide-instances.cabal
  bittide/bittide.cabal
  bittide/src/Bittide/ProcessingElement.hs
  bittide/src/Bittide/Wishbone.hs
  bittide/tests/Tests/Wishbone.hs
  cabal.project
  cabal.project.freeze
Labels: needs review

#493 Enable multiple threads when compiling sources
  cabal.project
Labels: needs review, salt

#509 Improve the clock reports
  bittide-experiments/src/Bittide/Report/ClockControl.hs
  bittide-instances/src/Bittide/Instances/Hitl/HwCcTopologies.hs
  bittide-tools/bittide-tools.cabal
  bittide-tools/clockcontrol/plot/Main.hs
  bittide-tools/clockcontrol/sim/src/Main.hs
Labels: needs review

#514 Re-enable reframing for simulation
  bittide-experiments/src/Bittide/Simulate/Config.hs
Labels: CI

#515 Align exported EB data with the selected topology
  bittide-experiments/src/Bittide/Plot.hs
  bittide-tools/clockcontrol/plot/Main.hs
Labels: needs review
