Repository bittide/bittide-hardware, pull requests merged in 2024-08, with the labels that each got.

#505 Add rust logging
  firmware-binaries/Cargo.lock
  firmware-support/Cargo.lock
  firmware-support/bittide-sys/Cargo.toml
  firmware-support/bittide-sys/src/uart.rs
  firmware-support/bittide-sys/src/uart/log.rs
  host-tools/Cargo.lock
Labels: 1

#256 Add wishbone packet buffers
  bittide-instances/bittide-instances.cabal
  bittide-instances/tests/Wishbone/Axi.hs
  bittide-instances/tests/Wishbone/Time.hs
  bittide-instances/tests/unittests.hs
  bittide/bittide.cabal
  bittide/src/Bittide/Axi4.hs
  bittide/src/Bittide/Axi4/Internal.hs
  bittide/src/Data/Constraint/Nat/Extra.hs
  bittide/tests/Tests/Axi4.hs
  bittide/tests/Tests/Axi4/Generators.hs
  bittide/tests/Tests/Axi4/Properties.hs
  bittide/tests/Tests/Axi4/Types.hs
  bittide/tests/Tests/Haxioms.hs
  bittide/tests/Tests/Shared.hs
  bittide/tests/Tests/Wishbone.hs
  bittide/tests/UnitTests.hs
  cabal.project
  firmware-binaries/Cargo.lock
  firmware-binaries/Cargo.toml
  firmware-binaries/test-cases/axi_stream_self_test/Cargo.toml
  firmware-binaries/test-cases/axi_stream_self_test/build.rs
  firmware-binaries/test-cases/axi_stream_self_test/memory.x
  firmware-binaries/test-cases/axi_stream_self_test/rust-toolchain.toml
  firmware-binaries/test-cases/axi_stream_self_test/src/main.rs
  firmware-support/Cargo.lock
  firmware-support/bittide-sys/Cargo.toml
  firmware-support/bittide-sys/src/axi.rs
  firmware-support/bittide-sys/src/axi/self_test.rs
  firmware-support/bittide-sys/src/lib.rs
  host-tools/Cargo.lock
Labels: 2, 2024H1

#511 Smoltcp bitide instance
  bittide-instances/bittide-instances.cabal
  bittide-instances/data/constraints/jtag_config.xdc
  bittide-instances/data/constraints/jtag_pmod0.xdc
  bittide-instances/data/constraints/jtag_pmod1.xdc
  bittide-instances/data/constraints/sgmii.xdc
  bittide-instances/data/constraints/vexRiscEthernet.xdc
  bittide-instances/data/constraints/vexRiscvTest.xdc
  bittide-instances/src/Bittide/Instances/Domains.hs
  bittide-instances/src/Bittide/Instances/Pnr/Ethernet.hs
  bittide-shake/exe/Main.hs
  bittide-shake/src/Clash/Shake/Vivado.hs
  bittide/bittide.cabal
  bittide/src/Bittide/Ethernet/Mac.hs
  cabal.project
  firmware-support/bittide-sys/src/lib.rs
  firmware-support/bittide-sys/src/mac.rs
Labels: 3, 2024H1

#606 Flip sign of `fsToPpm` output
  bittide-experiments/src/Bittide/Plot.hs
Labels: needs review, 1

#605 Use `GthTx` as assumed domain diff domain
  .github/simulation/staging.json
  .github/workflows/ci.yml
  bittide-experiments/src/Bittide/Report/ClockControl.hs
  bittide-experiments/src/Bittide/Simulate.hs
  bittide-experiments/src/Bittide/Simulate/Config.hs
  bittide-instances/src/Bittide/Instances/Hitl/FullMeshHwCc.hs
  bittide-instances/src/Bittide/Instances/Hitl/FullMeshSwCc.hs
  bittide-instances/src/Bittide/Instances/Hitl/HwCcTopologies.hs
  bittide-tools/clockcontrol/plot/Main.hs
  bittide-tools/clockcontrol/sim/src/Main.hs
Labels: 1

#610 Shift Y-axis according to clock offsets
  bittide-experiments/src/Bittide/Plot.hs
  bittide-experiments/src/Bittide/Report/ClockControl.hs
  bittide-experiments/src/Bittide/Simulate.hs
  bittide-tools/clockcontrol/plot/Main.hs
Labels: needs review

#618 Remove unit juggling
  bittide-experiments/src/Bittide/Plot.hs
  bittide-experiments/src/Bittide/Report/ClockControl.hs
  bittide-experiments/src/Bittide/Simulate/Config.hs
  bittide-instances/src/Bittide/Instances/Hitl/HwCcTopologies.hs
  bittide-instances/src/Bittide/Instances/Hitl/IlaPlot.hs
  bittide-tools/clockcontrol/plot/Main.hs
  bittide/bittide.cabal
  bittide/src/Bittide/Arithmetic/PartsPer.hs
Labels: needs review

#619 Add label to Y-axis for buffer occupancy plots
  bittide-experiments/src/Bittide/Plot.hs
Labels: needs review

#520 Instantiate core for temperature readouts
  .github/synthesis/all.json
  bittide-instances/bittide-instances.cabal
  bittide-instances/data/constraints/temperatureMonitor.xdc
  bittide-instances/src/Bittide/Instances/Hitl/TemperatureMonitor.hs
  bittide-instances/src/Bittide/Instances/Hitl/Tests.hs
  bittide-shake/exe/Main.hs
  bittide/bittide.cabal
  bittide/src/Clash/Cores/Xilinx/SystemMonitor.hs
Labels: needs review, 2024H1
