Repository bittide/bittide-hardware, pull requests merged in 2025-03, with the labels that each got.

#730 Bump Tasty to 1.5
  bittide/bittide.cabal
  cabal.project
  cabal.project.freeze
Labels: needs review

#722 Add handshake signals to transceivers
  bittide/bittide.cabal
  bittide/src/Bittide/Transceiver.hs
  bittide/tests/Tests/Transceiver.hs
Labels: needs review, switch

#734 Add synthesis caching to CI
  .github/scripts/cache.py
  .github/workflows/ci.yml
  bittide-shake/exe/Main.hs
  vivado-hs/src/Vivado/Internal.hs
Labels: needs review

#736 Add stage to cache key prefix
  .github/workflows/ci.yml
Labels: CI
